title: Open Hardware Makers Curriculum
subtitle:
email:
twitter: https://twitter.com/openHWmakers
chat:
description: > # this means to ignore newlines until "baseurl:"
  Open Hardware Makers is a mentorship program teaching best practices for Open Source Hardware
baseurl: "/OHM-curriculum" # the subpath of your site, e.g. /blog
url: "https://openhardware.space" # the base hostname & protocol for your site
github:
  repo: "ohwmakers/OHM-curriculum"
  branch: "gh-pages"


collections:
  articles:
    output: true
permalink: /:path/

# Build settings
markdown: kramdown

redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]

# variables
video: "<span class=\"video-player\"></span>"
assignment: "<span class=\"assignment\">Assignment: </span>"
theme: jekyll-theme-minimal
