title: Open Leadership Training Series
subtitle:
email: abby@mozillafoundation.org
description: > # this means to ignore newlines until "baseurl:"
  Does your MozFest session involve hands-on, project based learning? This
  training is for anyone running an open project at MozFest. This can be
  software, curriculum, or anything you can build together with a group.
baseurl: "/open-leadership-training-series" # the subpath of your site, e.g. /blog
url: "https://acabunoc.github.io" # the base hostname & protocol for your site
github:
  repo: "acabunoc/open-leadership-training-series"
  branch: "gh-pages"


collections:
  articles:
    output: true
permalink: /:path/

# Build settings
markdown: kramdown

redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]